//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_REST_SOAP.WCF_Soap_Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_Soap_Services.IAluguer")]
    public interface IAluguer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguer/AddAluguer", ReplyAction="http://tempuri.org/IAluguer/AddAluguerResponse")]
        bool AddAluguer(string email, string marca, string modelo, string dataIn, string dataOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguer/AddAluguer", ReplyAction="http://tempuri.org/IAluguer/AddAluguerResponse")]
        System.Threading.Tasks.Task<bool> AddAluguerAsync(string email, string marca, string modelo, string dataIn, string dataOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguer/ProcuraAlugueres", ReplyAction="http://tempuri.org/IAluguer/ProcuraAlugueresResponse")]
        string ProcuraAlugueres(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguer/ProcuraAlugueres", ReplyAction="http://tempuri.org/IAluguer/ProcuraAlugueresResponse")]
        System.Threading.Tasks.Task<string> ProcuraAlugueresAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguer/UpdateAluguer", ReplyAction="http://tempuri.org/IAluguer/UpdateAluguerResponse")]
        bool UpdateAluguer(string id_aluguer, string nome_marca, string nome_modelo, string datain, string dataout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguer/UpdateAluguer", ReplyAction="http://tempuri.org/IAluguer/UpdateAluguerResponse")]
        System.Threading.Tasks.Task<bool> UpdateAluguerAsync(string id_aluguer, string nome_marca, string nome_modelo, string datain, string dataout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguer/EliminaAluguer", ReplyAction="http://tempuri.org/IAluguer/EliminaAluguerResponse")]
        bool EliminaAluguer(string id_aluguer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguer/EliminaAluguer", ReplyAction="http://tempuri.org/IAluguer/EliminaAluguerResponse")]
        System.Threading.Tasks.Task<bool> EliminaAluguerAsync(string id_aluguer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAluguerChannel : Client_REST_SOAP.WCF_Soap_Services.IAluguer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AluguerClient : System.ServiceModel.ClientBase<Client_REST_SOAP.WCF_Soap_Services.IAluguer>, Client_REST_SOAP.WCF_Soap_Services.IAluguer {
        
        public AluguerClient() {
        }
        
        public AluguerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AluguerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AluguerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AluguerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddAluguer(string email, string marca, string modelo, string dataIn, string dataOut) {
            return base.Channel.AddAluguer(email, marca, modelo, dataIn, dataOut);
        }
        
        public System.Threading.Tasks.Task<bool> AddAluguerAsync(string email, string marca, string modelo, string dataIn, string dataOut) {
            return base.Channel.AddAluguerAsync(email, marca, modelo, dataIn, dataOut);
        }
        
        public string ProcuraAlugueres(string email) {
            return base.Channel.ProcuraAlugueres(email);
        }
        
        public System.Threading.Tasks.Task<string> ProcuraAlugueresAsync(string email) {
            return base.Channel.ProcuraAlugueresAsync(email);
        }
        
        public bool UpdateAluguer(string id_aluguer, string nome_marca, string nome_modelo, string datain, string dataout) {
            return base.Channel.UpdateAluguer(id_aluguer, nome_marca, nome_modelo, datain, dataout);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAluguerAsync(string id_aluguer, string nome_marca, string nome_modelo, string datain, string dataout) {
            return base.Channel.UpdateAluguerAsync(id_aluguer, nome_marca, nome_modelo, datain, dataout);
        }
        
        public bool EliminaAluguer(string id_aluguer) {
            return base.Channel.EliminaAluguer(id_aluguer);
        }
        
        public System.Threading.Tasks.Task<bool> EliminaAluguerAsync(string id_aluguer) {
            return base.Channel.EliminaAluguerAsync(id_aluguer);
        }
    }
}
